export const checkoutConstants =
{
    FETCH_CHECKOUT_ORDER_BEGIN: 'FETCH_ORDER_BEGIN',
    FETCH_CHECKOUT_ORDER_SUCCESS: 'FETCH_ORDER_SUCCESS',
    FETCH_CHECKOUT_ORDER_ERROR: 'FETCH_ORDER_ERROR',

    FETCH_CUSTOMER_BEGIN: 'FETCH_CUSTOMER_BEGIN',
    FETCH_CUSTOMER_SUCCESS: 'FETCH_CUSTOMER_SUCCESS',
    FETCH_CUSTOMER_ERROR: 'FETCH_CUSTOMER_ERROR',
};
