export const checkoutConstants = {
  UPDATE_SHIPPING_ADDRESS: "UPDATE_SHIPPING_ADDRESS",
  UPDATE_BILLING_ADDRESS: "UPDATE_BILLING_ADDRESS",
  UPDATE_PAYMENT_ORDER: "UPDATE_PAYMENT_ORDER",

  FETCH_ORDER_BEGIN: "FETCH_ORDER_BEGIN",
  FETCH_ORDER_SUCCESS: "FETCH_ORDER_SUCCESS",
  FETCH_ORDER_ERROR: "FETCH_ORDER_ERROR",

  FETCH_CUSTOMER_BEGIN: "FETCH_CUSTOMER_BEGIN",
  FETCH_CUSTOMER_SUCCESS: "FETCH_CUSTOMER_SUCCESS",
  FETCH_CUSTOMER_ERROR: "FETCH_CUSTOMER_ERROR",

  FETCH_ORDER_UPDATE_BEGIN: "FETCH_ORDER_UPDATE_BEGIN",
  FETCH_ORDER_UPDATE_SUCCESS: "FETCH_ORDER_UPDATE_SUCCESS",
  FETCH_ORDER_UPDATE_ERROR: "FETCH_ORDER_UPDATE_ERROR",

  UPDATE_BILLING: "UPDATE_BILLING",
  UPDATE_SHIPPING: "UPDATE_SHIPPING",
  UPDATE_GUEST_INFO: "UPDATE_GUEST_INFO",

  CLEAN_UP: "CLEANUP"
};
