export const checkoutAddressConstants = {
  REQUEST_CONTINUE: "REQUEST_CONTINUE",

  SHIPPING_CAN_CONTINUE: "SHIPPING_CAN_CONTINUE",
  BILLING_CAN_CONTINUE: "BILLING_CAN_CONTINUE",
  INFO_CAN_CONTINUE: "INFO_CAN_CONTINUE",

  PUT_INFO_BEGIN: "PUT_INFO_BEGIN",
  PUT_INFO_SUCCESS: "PUT_INFO_SUCCESS",
  PUT_INFO_ERROR: "PUT_INFO_ERROR",

  POST_SHIPPING_BEGIN: "POST_SHIPPING_BEGIN",
  POST_SHIPPING_SUCCESS: "POST_SHIPPING_SUCCESS",
  POST_SHIPPING_ERROR: "POST_SHIPPING_ERROR",

  POST_BILLING_BEGIN: "POST_BILLING_BEGIN",
  POST_BILLING_SUCCESS: "POST_BILLING_SUCCESS",
  POST_BILLING_ERROR: "POST_BILLING_ERROR",

  CLEAN_UP: "CLEAN_UP"
};
