export const PaymentConstants =
{
    FETCH_CARDS_BEGIN: 'FETCH_CARDS_BEGIN',
    FETCH_CARDS_SUCCESS: 'FETCH_CARDS_SUCCESS',
    FETCH_CARDS_ERROR: 'FETCH_CARDS_ERROR',

    POST_CARD_BEGIN: 'POST_CARD_BEGIN',
    POST_CARD_SUCCESS: 'POST_CARD_SUCCESS',
    POST_CARD_ERROR: 'POST_CARD_ERROR',

    DELETE_CARD_BEGIN: 'DELETE_CARD_BEGIN',
    DELETE_CARD_SUCCESS: 'DELETE_CARD_SUCCESS',
    DELETE_CARD_ERROR: 'DELETE_CARD_ERROR',

    ATTEMPT_PAYMENT_BEGIN: 'ATTEMPT_PAYMENT_BEGIN',
    ATTEMPT_PAYMENT_SUCCESS: 'ATTEMPT_PAYMENT_SUCCESS',
    ATTEMPT_PAYMENT_ERROR: 'ATTEMPT_PAYMENT_ERROR'
};