export const productManagementConstants =
{
    CHECK_PRIVILEGES_BEGIN: 'CHECK_PRIVILEGES_BEGIN',
    CHECK_PRIVILEGES_SUCCESS: 'CHECK_PRIVILEGES_SUCCESS',
    CHECK_PRIVILEGES_ERROR: 'CHECK_PRIVILEGES_ERROR',

    FETCH_PRODUCTS_BEGIN: 'FETCH_PRODUCTS_BEGIN',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',
    SET_NEW_PAGE: 'SET_NEW_PAGE',

    POST_PRODUCT_BEGIN: 'POST_PRODUCT_BEGIN',
    POST_PRODUCT_SUCCESS: 'POST_PRODUCT_SUCCESS',
    POST_PRODUCT_ERROR: 'POST_PRODUCT_ERROR',

    DELETE_PRODUCT_BEGIN: 'DELETE_PRODUCT_BEGIN',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR'
    
};