const productConstants =
{
  FETCH_PRODUCT_BEGIN: 'FETCH_PRODUCT_BEGIN',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  FETCH_PRODUCT_ERROR: 'FETCH_PRODUCT_ERROR',
};

export default productConstants;
